/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as NftNftSlugRouteImport } from './../routes/nft.$nftSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NftNftSlugRoute = NftNftSlugRouteImport.update({
  id: '/nft/$nftSlug',
  path: '/nft/$nftSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/nft/$nftSlug': typeof NftNftSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/nft/$nftSlug': typeof NftNftSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/nft/$nftSlug': typeof NftNftSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/nft/$nftSlug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/nft/$nftSlug'
  id: '__root__' | '/' | '/nft/$nftSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NftNftSlugRoute: typeof NftNftSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nft/$nftSlug': {
      id: '/nft/$nftSlug'
      path: '/nft/$nftSlug'
      fullPath: '/nft/$nftSlug'
      preLoaderRoute: typeof NftNftSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NftNftSlugRoute: NftNftSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
